export const TYPES = {
  LuaRuntime: Symbol.for("LuaRuntime"),
  MCPClientManager: Symbol.for("MCPClientManager"),
  TransportManager: Symbol.for("TransportManager"),
  SessionStore: Symbol.for("SessionStore"),
  AuthStrategy: Symbol.for("AuthStrategy"),
  ServerConfig: Symbol.for("ServerConfig"),
  Logger: Symbol.for("Logger"),
  ToolDiscoveryService: Symbol.for("ToolDiscoveryService"),
  ResourceAggregationService: Symbol.for("ResourceAggregationService"),
  PromptAggregationService: Symbol.for("PromptAggregationService"),
  MCPFormatterService: Symbol.for("MCPFormatterService"),
  MCPGatewayServer: Symbol.for("MCPGatewayServer"),
  MCPSessionController: Symbol.for("MCPSessionController"),
  ShutdownHandler: Symbol.for("ShutdownHandler"),
};
